# Generated by Django 5.2.7 on 2025-10-18 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название должности')),
            ],
            options={
                'verbose_name': 'должность',
                'verbose_name_plural': 'Должности',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=256, verbose_name='Отчество')),
                ('last_name', models.CharField(max_length=256, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='адрес электронной почты')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
                ('hired_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата приема на работу')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_workers', to=settings.AUTH_USER_MODEL, verbose_name='Создано')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workers', to='core.position', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['last_name', 'first_name', 'middle_name', 'id'],
            },
        ),
    ]
