# Generated by Django 5.2.7 on 2025-10-19 16:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
        migrations.AddIndex(
            model_name='worker',
            index=models.Index(fields=['is_active', 'position'], name='core_worker_is_acti_f124fd_idx'),
        ),
        migrations.AddIndex(
            model_name='worker',
            index=models.Index(fields=['last_name', 'first_name'], name='core_worker_last_na_f581b3_idx'),
        ),
    ]
